### PR TITLE
 fix typeerror failed to fetch data from api

### LINKED ISSUE #22: Fix TypeError: Failed to fetchSourceapp
- This error is preventing the products from being listed on the homepage

### PR DESCRIPTION
**Pull request by sangkips**
This error is preventing the products from being listed on the homepage

### CODE REVIEW

File: frontend/app/lib/api.ts [hunk 1]
```diff
@@ -1,28 +1,37 @@
-import { apiUrl } from "../utils/env";
+import { apiUrl } from "../utils/env"
```
Comment (etowett) [inline frontend/app/lib/api.ts:1]: Not sure why this `;` was removed, but we might want to create some unified linting settings to avoid these.

File: frontend/app/lib/api.ts [hunk 2]
```diff
@@ -1,28 +1,37 @@
...
 
 async function fetchWithAuth(endpoint: string, options: RequestInit = {}) {
-  const headers = new Headers(options.headers);
+  if (!apiUrl) {
+    throw new Error("API URL is not configured")
+  }
```
Comment (etowett) [inline frontend/app/lib/api.ts:6]: Since we are providing a default value when the api is not provided, this shouldn't be necessary, but it doesn't harm.

File: frontend/app/lib/api.ts [hunk 3]
```diff
@@ -1,28 +1,37 @@
...
+
+    if (!response.ok) {
+      const error = await response.json().catch(() => ({}))
+      throw new Error(error.error || `HTTP error! status: ${response.status}`)
+    }
 
-  return response.json();
+    return response.json()
+  } catch (error) {
+    throw error
```
Comment (etowett) [inline frontend/app/lib/api.ts:27]: We can even add more context into the rethrown error, or no need to just catch and rethrow as is

File: frontend/app/lib/api.ts [hunk 4]
```diff
@@ -1,28 +1,37 @@
...
 export const fetchProducts = async ({ page, limit }: { page?: number; limit?: number }) => {
-  return fetchWithAuth(`/products/?page=${page}&limit=${limit}`);
-};
+  return fetchWithAuth(`/products/?page=${page || 1}&limit=${limit || 10}`)
+}
 
 export const fetchProduct = async (id: string) => {
   return fetchWithAuth(`/products/${id}`);
-};
+};
```
Comment (etowett) [inline frontend/app/lib/api.ts:37]: We should add end of line to avoid this

**Review by etowett — COMMENTED** [review]
Good stuff
